/**
 * Dump the seeded SQLite database into a static TypeScript data module.
 *
 * Run:  bun run scripts/dump-content.ts
 *
 * Why: Vercel serverless functions cannot host a SQLite file reliably, so the
 * entire content library (courses, news, resources, …) is frozen into
 * src/data/content.ts and served from memory by the API routes. Re-run this
 * script after changing the seed data.
 */
import { PrismaClient } from '@prisma/client'
import { writeFileSync } from 'node:fs'
import path from 'node:path'

const db = new PrismaClient()

function j(value: unknown): string {
  return JSON.stringify(value, null, 2)
}

async function main() {
  const [courses, news, digests, resources, rankers, testimonials, books, series, plans, faqs, mcqs] =
    await Promise.all([
      db.course.findMany({ orderBy: [{ featured: 'desc' }, { feeInr: 'asc' }] }),
      db.newsArticle.findMany({ orderBy: [{ date: 'desc' }, { createdAt: 'asc' }] }),
      db.monthlyNewsDigest.findMany({ orderBy: [{ year: 'desc' }, { month: 'desc' }] }),
      db.resource.findMany({ orderBy: [{ category: 'asc' }, { title: 'asc' }] }),
      db.ranker.findMany({ orderBy: [{ year: 'desc' }, { rank: 'asc' }] }),
      db.testimonial.findMany({ orderBy: { name: 'asc' } }),
      db.book.findMany({ orderBy: { title: 'asc' } }),
      db.testSeries.findMany({ orderBy: { priceInr: 'desc' } }),
      db.plan.findMany({ orderBy: { priceInr: 'asc' } }),
      db.faq.findMany({ orderBy: { id: 'asc' } }),
      db.mcqQuestion.findMany({ orderBy: { createdAt: 'desc' } }),
    ])

  const parseArr = (raw: string | null): string[] => {
    if (!raw) return []
    try {
      const p = JSON.parse(raw)
      return Array.isArray(p) ? p.map(String) : []
    } catch {
      return []
    }
  }
  const parseObj = (raw: string | null): Record<string, unknown> | null => {
    if (!raw) return null
    try {
      const p = JSON.parse(raw)
      return p && typeof p === 'object' ? (p as Record<string, unknown>) : null
    } catch {
      return null
    }
  }

  const coursesOut = courses.map((c) => ({
    id: c.id,
    title: c.title,
    slug: c.slug,
    tagline: c.tagline,
    description: c.description,
    mode: c.mode,
    duration: c.duration,
    feeInr: c.feeInr,
    originalFeeInr: c.originalFeeInr,
    features: parseArr(c.featuresJson),
    syllabusHighlights: parseArr(c.syllabusJson),
    batchSize: c.batchSize,
    tag: c.tag,
    featured: c.featured,
    startDate: c.startDate,
    sessionsPerWeek: c.sessionsPerWeek,
  }))

  const newsOut = news.map((a) => {
    const mq = parseObj(a.mainsQuestionJson)
    const mainsQuestion =
      mq && typeof mq.text === 'string'
        ? {
            text: String(mq.text),
            marks: Number(mq.marks) || 10,
            words: Number(mq.words) || 150,
            directive: typeof mq.directive === 'string' ? mq.directive : undefined,
          }
        : null
    return {
      id: a.id,
      title: a.title,
      summary: a.summary,
      content: a.content,
      source: a.source,
      gsTag: a.gsTag,
      subject: a.subject,
      date: a.date,
      readMinutes: a.readMinutes,
      tags: parseArr(a.tagsJson),
      prelims: parseArr(a.prelimsJson),
      mains: parseArr(a.mainsJson),
      keywords: parseArr(a.keywordsJson),
      mainsQuestion,
    }
  })

  const digestsOut = digests.map((d) => ({
    id: d.id,
    month: d.month,
    year: d.year,
    fileName: d.fileName,
    fileUrl: d.fileUrl,
    status: d.status,
  }))

  const resourcesOut = resources.map((r) => ({ ...r }))
  const rankersOut = rankers.map((r) => ({ ...r }))
  const testimonialsOut = testimonials.map((t) => ({ ...t }))
  const booksOut = books.map((b) => ({ ...b }))
  const seriesOut = series.map((s) => ({ ...s, features: parseArr(s.featuresJson) }))
  const plansOut = plans.map((p) => ({ ...p, features: parseArr(p.featuresJson) }))
  const faqsOut = faqs.map((f) => ({ ...f }))
  const mcqsOut = mcqs.map((q) => ({
    id: q.id,
    question: q.question,
    options: parseArr(q.optionsJson),
    correctIndex: q.correctIndex,
    explanation: q.explanation,
    subject: q.subject,
    difficulty: q.difficulty,
  }))

  const out = `// AUTO-GENERATED by scripts/dump-content.ts — do not edit by hand.
// Source of truth: the seeded SQLite database. Re-generate with:
//   bun run scripts/dump-content.ts
//
// The whole content library lives in memory so the API routes run with zero
// database dependency (required for Vercel serverless, where a SQLite file
// cannot persist).

export interface CourseRecord {
  id: string
  title: string
  slug: string
  tagline: string
  description: string
  mode: string
  duration: string
  feeInr: number
  originalFeeInr: number | null
  features: string[]
  syllabusHighlights: string[]
  batchSize: string
  tag: string
  featured: boolean
  startDate: string
  sessionsPerWeek: number
}

export interface MainsQuestionRecord {
  text: string
  marks: number
  words: number
  directive?: string
}

export interface NewsRecord {
  id: string
  title: string
  summary: string
  content: string
  source: string
  gsTag: string
  subject: string
  date: string
  readMinutes: number
  tags: string[]
  prelims: string[]
  mains: string[]
  keywords: string[]
  mainsQuestion: MainsQuestionRecord | null
}

export interface MonthlyDigestRecord {
  id: string
  month: number
  year: number
  fileName: string
  fileUrl: string
  status: string
}

export interface ResourceRecord {
  id: string
  title: string
  category: string
  exam: string
  description: string
  year: number | null
  fileType: string
  pages: number | null
  downloads: number
  slug: string
  contentSummary: string
}

export interface RankerRecord {
  id: string
  name: string
  year: number
  rank: number
  service: string
  optional: string
  quote: string
  avatarSeed: string
}

export interface TestimonialRecord {
  id: string
  name: string
  batch: string
  role: string
  quote: string
  rating: number
}

export interface BookRecord {
  id: string
  title: string
  author: string
  priceInr: number
  mrpInr: number
  category: string
  description: string
  rating: number
  coverColor: string
  slug: string
}

export interface TestSeriesRecord {
  id: string
  title: string
  exam: string
  totalTests: number
  freeTests: number
  priceInr: number
  features: string[]
  description: string
  slug: string
}

export interface PlanRecord {
  id: string
  name: string
  priceInr: number
  period: string
  tagline: string
  features: string[]
  highlight: boolean
  aiCredits: string
}

export interface FaqRecord {
  id: string
  question: string
  answer: string
  category: string
}

export interface McqRecord {
  id: string
  question: string
  options: string[]
  correctIndex: number
  explanation: string
  subject: string
  difficulty: string
}

export const COURSES: CourseRecord[] = ${j(coursesOut)}

export const NEWS_ARTICLES: NewsRecord[] = ${j(newsOut)}

export const MONTHLY_DIGESTS: MonthlyDigestRecord[] = ${j(digestsOut)}

export const RESOURCES: ResourceRecord[] = ${j(resourcesOut)}

export const RANKERS: RankerRecord[] = ${j(rankersOut)}

export const TESTIMONIALS: TestimonialRecord[] = ${j(testimonialsOut)}

export const BOOKS: BookRecord[] = ${j(booksOut)}

export const TEST_SERIES: TestSeriesRecord[] = ${j(seriesOut)}

export const PLANS: PlanRecord[] = ${j(plansOut)}

export const FAQS: FaqRecord[] = ${j(faqsOut)}

export const MCQ_BANK: McqRecord[] = ${j(mcqsOut)}

/** Latest edition date in the news archive (YYYY-MM-DD), null when empty. */
export const LATEST_NEWS_DATE: string | null =
  NEWS_ARTICLES.length > 0
    ? NEWS_ARTICLES.reduce((max, a) => (a.date > max ? a.date : max), NEWS_ARTICLES[0].date)
    : null
`

  const target = path.join(process.cwd(), 'src', 'data', 'content.ts')
  writeFileSync(target, out)
  console.log(
    `Wrote ${target}: ${coursesOut.length} courses, ${newsOut.length} news, ${digestsOut.length} digests, ${resourcesOut.length} resources, ${rankersOut.length} rankers, ${testimonialsOut.length} testimonials, ${booksOut.length} books, ${seriesOut.length} test-series, ${plansOut.length} plans, ${faqsOut.length} faqs, ${mcqsOut.length} mcqs`
  )
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(() => db.$disconnect())
